hostnames:
  mgmt-rtr:
    ip: "10.10.10.1"
    os: "ios"
  reg-rtr:
    ip: "10.10.10.2"
    os: "ios"
  ham-rtr:
    ip: "10.10.10.3"
    os: "ios"
  mid-rtr:
    ip: "10.10.10.4"
    os: "ios"
  mgmt-sw:
    ip: "10.10.10.5"
    os: "ios"
  ham-sw:
    ip: "10.10.10.6"
    os: "ios"
  mid-sw:
    ip: "10.10.10.7"
    os: "ios"
  jenkins-server:
    ip: "10.10.10.10"
    os: "linux"
  ham-l:
    ip: "10.10.10.11"
    os: "linux"
  mid-l:
    ip: "10.10.10.12"
    os: "linux"
  oxf-l:
    ip: "10.10.10.13"
    os: "linux"
  mid-w:
    ip: "10.10.10.14"
    os: "windows"
  ham-w:
    ip: "10.10.10.15"
    os: "windows"
